import React from 'react';
import { LegalLayout } from '../components/ui/legal-layout';

export const Terms = () => {
  return (
    <LegalLayout
      title="Terms of Service"
      lastUpdated={new Date().toLocaleDateString()}
      icon="file"
    >
      <div className="space-y-12 text-zinc-300">
        <section>
          <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="flex items-center justify-center w-8 h-8 rounded-full bg-indigo-500/10 text-indigo-400 text-sm font-bold border border-indigo-500/20">1</span>
            Introduction
          </h2>
          <p className="leading-relaxed text-zinc-400">
            Welcome to Loom.ai. By accessing or using our website and services, you agree to be bound by these Terms and Conditions. If you disagree with any part of the terms, then you may not access the service.
          </p>
        </section>

        <div className="h-px bg-white/5" />

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="flex items-center justify-center w-8 h-8 rounded-full bg-indigo-500/10 text-indigo-400 text-sm font-bold border border-indigo-500/20">2</span>
            Use of Service
          </h2>
          <p className="leading-relaxed text-zinc-400 mb-4">
            You agree to use Loom.ai only for lawful purposes and in accordance with these Terms. You are responsible for all content you generate using our AI tools.
          </p>
          <ul className="space-y-2 list-disc list-inside text-zinc-400 ml-4">
            <li>You must not use the service to generate harmful or illegal content.</li>
            <li>You must not attempt to reverse engineer the service.</li>
            <li>You are responsible for maintaining the security of your account.</li>
          </ul>
        </section>

        <div className="h-px bg-white/5" />

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="flex items-center justify-center w-8 h-8 rounded-full bg-indigo-500/10 text-indigo-400 text-sm font-bold border border-indigo-500/20">3</span>
            Intellectual Property
          </h2>
          <p className="leading-relaxed text-zinc-400">
            The content generated by Loom.ai is yours to use. However, the underlying technology, design, and branding of Loom.ai remain our exclusive property. You retain all rights to your input data.
          </p>
        </section>

        <div className="h-px bg-white/5" />

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-3">
            <span className="flex items-center justify-center w-8 h-8 rounded-full bg-indigo-500/10 text-indigo-400 text-sm font-bold border border-indigo-500/20">4</span>
            Limitation of Liability
          </h2>
          <p className="leading-relaxed text-zinc-400">
            Loom.ai is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to direct, indirect, incidental, punitive, and consequential damages.
          </p>
        </section>
      </div>
    </LegalLayout>
  );
};
